[2024-05-08T15:29:01.258+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T15:28:39.828713+00:00 [queued]>
[2024-05-08T15:29:01.270+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T15:28:39.828713+00:00 [queued]>
[2024-05-08T15:29:01.271+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-08T15:29:01.291+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_and_clean_data_task> on 2024-05-08 15:28:39.828713+00:00
[2024-05-08T15:29:01.299+0000] {standard_task_runner.py:60} INFO - Started process 1281 to run task
[2024-05-08T15:29:01.306+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_and_clean_data_task', 'manual__2024-05-08T15:28:39.828713+00:00', '--job-id', '506', '--raw', '--subdir', 'DAGS_FOLDER/how.py', '--cfg-path', '/tmp/tmplp0kgv5a']
[2024-05-08T15:29:01.309+0000] {standard_task_runner.py:88} INFO - Job 506: Subtask process_and_clean_data_task
[2024-05-08T15:29:01.374+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_and_clean_data_task manual__2024-05-08T15:28:39.828713+00:00 [running]> on host 8aebc95d8de6
[2024-05-08T15:29:01.474+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_and_clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T15:28:39.828713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-08T15:28:39.828713+00:00'
[2024-05-08T15:29:01.477+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: process_and_clean_data() missing 1 required positional argument: 'song_list'
[2024-05-08T15:29:01.490+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=process_and_clean_data_task, execution_date=20240508T152839, start_date=20240508T152901, end_date=20240508T152901
[2024-05-08T15:29:01.509+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 506 for task process_and_clean_data_task (process_and_clean_data() missing 1 required positional argument: 'song_list'; 1281)
[2024-05-08T15:29:01.519+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-08T15:29:01.549+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
