[2024-05-06T12:50:04.729+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T12:48:44.481636+00:00 [queued]>
[2024-05-06T12:50:04.737+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T12:48:44.481636+00:00 [queued]>
[2024-05-06T12:50:04.738+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-06T12:50:04.753+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_song_info> on 2024-05-06 12:48:44.481636+00:00
[2024-05-06T12:50:04.759+0000] {standard_task_runner.py:60} INFO - Started process 1240 to run task
[2024-05-06T12:50:04.763+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_song_info', 'manual__2024-05-06T12:48:44.481636+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpzsq4i8g9']
[2024-05-06T12:50:04.765+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask process_song_info
[2024-05-06T12:50:04.811+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T12:48:44.481636+00:00 [running]> on host 903c75f80f15
[2024-05-06T12:50:04.950+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_song_info' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T12:48:44.481636+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T12:48:44.481636+00:00'
[2024-05-06T12:50:04.952+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_song_info() missing 1 required positional argument: 'idx'
[2024-05-06T12:50:04.960+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=process_song_info, execution_date=20240506T124844, start_date=20240506T125004, end_date=20240506T125004
[2024-05-06T12:50:04.975+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 132 for task process_song_info (get_song_info() missing 1 required positional argument: 'idx'; 1240)
[2024-05-06T12:50:05.016+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T12:50:05.036+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
