[2024-05-06T08:06:12.415+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:05:53.239930+00:00 [queued]>
[2024-05-06T08:06:12.425+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:05:53.239930+00:00 [queued]>
[2024-05-06T08:06:12.426+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-06T08:06:12.441+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_song_info> on 2024-05-06 08:05:53.239930+00:00
[2024-05-06T08:06:12.448+0000] {standard_task_runner.py:60} INFO - Started process 2982 to run task
[2024-05-06T08:06:12.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_song_info', 'manual__2024-05-06T08:05:53.239930+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpnf806n1a']
[2024-05-06T08:06:12.453+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask process_song_info
[2024-05-06T08:06:12.509+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:05:53.239930+00:00 [running]> on host 903c75f80f15
[2024-05-06T08:06:12.596+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_song_info' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T08:05:53.239930+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T08:05:53.239930+00:00'
[2024-05-06T08:06:12.598+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_song_info() missing 2 required positional arguments: 'song' and 'idx'
[2024-05-06T08:06:12.608+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=process_song_info, execution_date=20240506T080553, start_date=20240506T080612, end_date=20240506T080612
[2024-05-06T08:06:12.621+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 78 for task process_song_info (get_song_info() missing 2 required positional arguments: 'song' and 'idx'; 2982)
[2024-05-06T08:06:12.664+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T08:06:12.692+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
