[2024-05-06T08:09:48.617+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:09:31.116611+00:00 [queued]>
[2024-05-06T08:09:48.629+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:09:31.116611+00:00 [queued]>
[2024-05-06T08:09:48.630+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-06T08:09:48.646+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_song_info> on 2024-05-06 08:09:31.116611+00:00
[2024-05-06T08:09:48.654+0000] {standard_task_runner.py:60} INFO - Started process 3072 to run task
[2024-05-06T08:09:48.658+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'process_song_info', 'manual__2024-05-06T08:09:31.116611+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp9zqfoni8']
[2024-05-06T08:09:48.660+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask process_song_info
[2024-05-06T08:09:48.714+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.process_song_info manual__2024-05-06T08:09:31.116611+00:00 [running]> on host 903c75f80f15
[2024-05-06T08:09:48.805+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='process_song_info' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T08:09:31.116611+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T08:09:31.116611+00:00'
[2024-05-06T08:09:48.808+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: get_song_info() missing 2 required positional arguments: 'song' and 'idx'
[2024-05-06T08:09:48.817+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=process_song_info, execution_date=20240506T080931, start_date=20240506T080948, end_date=20240506T080948
[2024-05-06T08:09:48.832+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task process_song_info (get_song_info() missing 2 required positional arguments: 'song' and 'idx'; 3072)
[2024-05-06T08:09:48.871+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T08:09:48.898+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
