[2024-05-06T05:44:55.020+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [queued]>
[2024-05-06T05:44:55.037+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [queued]>
[2024-05-06T05:44:55.085+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-06T05:44:55.117+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_token> on 2024-05-06 05:44:52.611987+00:00
[2024-05-06T05:44:55.125+0000] {standard_task_runner.py:60} INFO - Started process 685 to run task
[2024-05-06T05:44:55.129+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'get_token', 'manual__2024-05-06T05:44:52.611987+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp55nhfq7a']
[2024-05-06T05:44:55.130+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask get_token
[2024-05-06T05:44:55.196+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [running]> on host 903c75f80f15
[2024-05-06T05:44:55.287+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T05:44:52.611987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T05:44:52.611987+00:00'
[2024-05-06T05:44:55.291+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 27, in get_token
    auth_string = client_id + ":" + client_secret
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-05-06T05:44:55.307+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=get_token, execution_date=20240506T054452, start_date=20240506T054455, end_date=20240506T054455
[2024-05-06T05:44:55.325+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task get_token (unsupported operand type(s) for +: 'NoneType' and 'str'; 685)
[2024-05-06T05:44:55.342+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T05:44:55.388+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
