[2024-05-06T05:46:22.097+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [queued]>
[2024-05-06T05:46:22.112+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [queued]>
[2024-05-06T05:46:22.113+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-06T05:46:22.139+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_token> on 2024-05-06 05:44:52.611987+00:00
[2024-05-06T05:46:22.149+0000] {standard_task_runner.py:60} INFO - Started process 712 to run task
[2024-05-06T05:46:22.153+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'get_token', 'manual__2024-05-06T05:44:52.611987+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmpyhvrnatp']
[2024-05-06T05:46:22.155+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask get_token
[2024-05-06T05:46:22.238+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.get_token manual__2024-05-06T05:44:52.611987+00:00 [running]> on host 903c75f80f15
[2024-05-06T05:46:22.337+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T05:44:52.611987+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T05:44:52.611987+00:00'
[2024-05-06T05:46:22.339+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main15.py", line 27, in get_token
    auth_string = client_id + ":" + client_secret
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-05-06T05:46:22.357+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_data_pipeline, task_id=get_token, execution_date=20240506T054452, start_date=20240506T054622, end_date=20240506T054622
[2024-05-06T05:46:22.375+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task get_token (unsupported operand type(s) for +: 'NoneType' and 'str'; 712)
[2024-05-06T05:46:22.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T05:46:22.434+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
