[2024-05-06T07:43:51.297+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data_pipeline.search_playlist manual__2024-05-06T07:43:42.017388+00:00 [queued]>
[2024-05-06T07:43:51.310+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data_pipeline.search_playlist manual__2024-05-06T07:43:42.017388+00:00 [queued]>
[2024-05-06T07:43:51.311+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-06T07:43:51.329+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): search_playlist> on 2024-05-06 07:43:42.017388+00:00
[2024-05-06T07:43:51.336+0000] {standard_task_runner.py:60} INFO - Started process 2547 to run task
[2024-05-06T07:43:51.340+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_data_pipeline', 'search_playlist', 'manual__2024-05-06T07:43:42.017388+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/main15.py', '--cfg-path', '/tmp/tmp9z5olzh3']
[2024-05-06T07:43:51.342+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask search_playlist
[2024-05-06T07:43:51.399+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_data_pipeline.search_playlist manual__2024-05-06T07:43:42.017388+00:00 [running]> on host 903c75f80f15
[2024-05-06T07:43:51.505+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_data_pipeline' AIRFLOW_CTX_TASK_ID='search_playlist' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T07:43:42.017388+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T07:43:42.017388+00:00'
[2024-05-06T07:43:51.508+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: search_for_playlist() missing 1 required positional argument: 'token'
[2024-05-06T07:43:51.520+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data_pipeline, task_id=search_playlist, execution_date=20240506T074342, start_date=20240506T074351, end_date=20240506T074351
[2024-05-06T07:43:51.538+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task search_playlist (search_for_playlist() missing 1 required positional argument: 'token'; 2547)
[2024-05-06T07:43:51.553+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T07:43:51.585+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
